CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    vendor VARCHAR(120) NOT NULL,
    installed_version VARCHAR(80) NOT NULL,
    latest_version VARCHAR(80),
    version_source_url VARCHAR(500),
    check_strategy VARCHAR(40) NOT NULL,
    last_checked_at TIMESTAMP WITH TIME ZONE,
    last_check_status VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    notes VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_products_vendor_name UNIQUE (vendor, name),
    CONSTRAINT ck_products_check_strategy
        CHECK (check_strategy IN ('STATIC_JSON', 'GITHUB_RELEASES', 'MANUAL')),
    CONSTRAINT ck_products_last_check_status
        CHECK (last_check_status IN ('UP_TO_DATE', 'UPDATE_AVAILABLE', 'CHECK_FAILED', 'UNKNOWN'))
);

CREATE TABLE product_check_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    installed_version VARCHAR(80) NOT NULL,
    detected_version VARCHAR(80),
    status VARCHAR(40) NOT NULL,
    message VARCHAR(500) NOT NULL,
    CONSTRAINT ck_history_status
        CHECK (status IN ('UP_TO_DATE', 'UPDATE_AVAILABLE', 'CHECK_FAILED', 'UNKNOWN'))
);

CREATE INDEX idx_products_last_check_status ON products(last_check_status);
CREATE INDEX idx_products_last_checked_at ON products(last_checked_at);
CREATE INDEX idx_product_check_history_product_checked
    ON product_check_history(product_id, checked_at DESC);
